/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class StringsExportPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("exportStrings", StringsExportTask::class.java) {
            it.group = "Strings resource export tasks"
        }
    }
}
